# Supplier.create!([
#   {name: "Chicago Luxury Autosports", email: "ChicagoLuxuryAuto@AOL.com", phone_number: "666-123-4567"},
#   {name: "Russ Daddy's Supercars", email: "RussDaddyWhips@gmail.com", phone_number: "630-207-6107"},
#   {name: "DuPage Import Group", email: "BuyYourSuperCarInTheBurbs@AOL.com", phone_number: "708-987-1234"}
# ])

# Product.create!([
#   {name: "Audi R8", price: "165975.0", image_url: "https://i.ebayimg.com/00/s/NDgwWDY0MA==/z/n3QAAOSwU91ajD-7/$_20.JPG?set_id=8800005007", description: "The new Audi R8 Coupe shares many similarities with the Audi R8 GT3 LMS. Teams from the motorsports and production worked hand-in-hand, sharing just under 50% of the same parts as the R8 GT3 LMS race car. The main attraction of the R8 is the 5.2-liter V10 FSI® engine, which produces 532 hp of power and 398 lb-ft of torque. Taking it up a notch, the R8 V10 plus cranks out 602 hp and 413 lb-ft of torque. ", stock: true, supplier_id: nil},
#   {name: "Acura NSX", price: "156000.0", image_url: "https://media.wheelscene.com/wp-content/uploads/2016/05/First-2017-Acura-NSX-Delivered-880x503.jpg", description: "Draped in colors inspired by the spirit of racing and the subtleties of nature, the NSX is a work of precision-crafted art. The vivid, high-chroma finish emphasizes the car’s sculpted lines for a show-stopping look that turns heads whether it’s shredding the track or standing still.", stock: true, supplier_id: nil},
#   {name: "Lamborghini Aventador", price: "417650.0", image_url: "https://1-photos7.motorcar.com/new-2018-lamborghini-aventador-showcar-8868-16805712-3-1024.jpg", description: "Brutally powerful and obscenely flamboyant, the Aventador is unburdened by reality. Crazy expensive, it’s capable of amazing performance without feeling as if it’s going to spin out into a ditch, which is refreshing in a supercar. Available as an S coupe or S roadster, it has a 730-hp 6.5-liter V-12, a seven-speed automated-manual transmission, and all-wheel drive. To help put all that power to pavement, each Aventador has monstrous tires, rear-wheel steering, and adaptive suspension.", stock: true, supplier_id: nil},
#   {name: "McLaren 720S", price: "285000.0", image_url: "https://s1.cdn.autoevolution.com/images/news/mclaren-720s-lowered-on-novitec-mc1-wheels-looks-like-a-racecar-121389_1.jpg", description: "The McLaren 720S embodies our relentless quest to push the limits of possibility. Lighter, stronger, faster. It’s all of these and more. But how it makes you feel is altogether something else. Prepare to push the limits of what you thought possible in a supercar.", stock: true, supplier_id: nil},
#   {name: "Koenigsegg One 1", price: "2850000.0", image_url: "http://www.thesupercarblog.com/wp-content/uploads/2016/08/2015-Koenigsegg-One-1-for-sale-in-USA-10.jpg", description: "The One:1 was introduced in 2014. Seven examples, including one prototype, were built during 2014 and 2015.\n\nThis was one of the most exclusive production car programs ever envisaged in the car industry.\n\nThe hp-to-kg curb weight ratio is an astonishing 1:1. This is the “dream” equation, previously thought impossible when it comes to fully road legal and usable sports cars. The One:1 is the first homologated production car in the world with one Megawatt of power, thereby making it the world´s first series produced Megacar.\n\nThus, the name One:1.\n\n", stock: true, supplier_id: nil},
#   {name: "Ford GT", price: "450000.0", image_url: "https://www.ford.com/campaignlibs/content/dam/ford_com/gtreveal/config_images/FordGT_Config_1440px.jpg", description: "Innovation. That’s what the Ford GT is all about. From its aerodynamically optimized shape to its multifunctional buttresses to its extraordinarily powerful 3.5L EcoBoost® V6 engine, everything about the Ford GT is designed to deliver pure performance.", stock: true, supplier_id: nil},
#   {name: "Bugatti Veyron 16.4 SS", price: "2400000.0", image_url: "https://rmsothebys-cache.azureedge.net/c/8/8/1/0/2/c88102723fad47d34d8c3a286ac13cd539e6498d.jpg", description: "bugatti continued the brand tradition of developing super sport versions of successful models with the veyron 16.4 super sport. the veyron 16.4 super sport expanded the limits of possibility in the automotive sector even further and set new benchmarks.", stock: true, supplier_id: nil},
#   {name: "Ferrari 488 GTB", price: "256550.0", image_url: "http://2pus8t1yk38z3kihxp31m2fa.wpengine.netdna-cdn.com/wp-content/uploads/2018/03/Ferrari-488-GTB-Vossen-Forged-Series-17-S17-01-%C2%A9-Vossen-Wheels-2018-1001-1047x698.jpg", description: "The 488 GTB name marks a return to the classic Ferrari model designation with the 488 in its moniker indicating the engine's unitary displacement, while the GTB stands for Gran Turismo Berlinetta. The new car not only delivers unparalleled performance, it also makes that extreme power exploitable and controllable to an unprecedented level even by less expert drivers.", stock: true, supplier_id: nil}
# ])


ProductCategory.create(product_id:9,6, category_id:2 )


